-- Neo — the list of makes.
--
-- Run ONCE, after schema.sql. Fills public.makes with every manufacturer the
-- site knows about (102 rows). `name` is exactly as supplied; `display_name`
-- is how the site spells it. Ids are assigned by the database.
--
-- Safe to re-run: rows that already exist are left alone, so edits made since
-- are kept.

insert into public.makes (name, display_name, country)
values
  ('ACURA', 'Acura', 'USA'),
  ('ALFA ROMEO', 'Alfa Romeo', 'ITALY'),
  ('ASTON MARTIN', 'Aston Martin', 'ENGLAND'),
  ('AUDI', 'Audi', 'GERMANY'),
  ('AUSTIN', 'Austin', 'ENGLAND'),
  ('AUTO BIANCHI', 'Auto Bianchi', 'ITALY'),
  ('BENTLEY', 'Bentley', 'ENGLAND'),
  ('BIRKIN', 'Birkin', 'HOLLAND'),
  ('BMW', 'BMW', 'GERMANY'),
  ('BMW ALPINA', 'BMW Alpina', 'GERMANY'),
  ('BUICK', 'Buick', 'USA'),
  ('CADILLAC', 'Cadillac', 'USA'),
  ('CATERPILLAR', 'Caterpillar', 'USA'),
  ('CHEVROLET', 'Chevrolet', 'USA'),
  ('CHRYSLER', 'Chrysler', 'USA'),
  ('CITROEN', 'Citroen', 'FRANCE'),
  ('CT&T', 'CT&T', 'KOREA'),
  ('DAEWOO', 'Daewoo', 'KOREA'),
  ('DAIHATSU', 'Daihatsu', 'JAPAN'),
  ('DAIMLER', 'Daimler', 'ENGLAND'),
  ('DODGE', 'Dodge', 'USA'),
  ('DONKERVOORT', 'Donkervoort', 'HOLLAND'),
  ('EUROPEAN FORD', 'European Ford', 'GERMANY'),
  ('FERRARI', 'Ferrari', 'ITALY'),
  ('FIAT', 'Fiat', 'ITALY'),
  ('FORD', 'Ford', 'USA'),
  ('FORD JAPAN', 'Ford Japan', 'JAPAN'),
  ('FUJI HEAVY', 'Fuji Heavy', 'JAPAN'),
  ('GMC', 'GMC', 'USA'),
  ('HANIX', 'Hanix', 'JAPAN'),
  ('HARLEY DAVIDSON', 'Harley-Davidson', 'USA'),
  ('HINO', 'Hino', 'JAPAN'),
  ('HITACHI', 'Hitachi', 'JAPAN'),
  ('HONDA', 'Honda', 'JAPAN'),
  ('HUMMER', 'Hummer', 'USA'),
  ('HYUNDAI', 'Hyundai', 'KOREA'),
  ('INFINITI', 'Infiniti', 'USA'),
  ('INTERNATIONAL', 'International', 'USA'),
  ('ISEKI', 'Iseki', 'JAPAN'),
  ('ISUZU', 'Isuzu', 'JAPAN'),
  ('JAGUAR', 'Jaguar', 'ENGLAND'),
  ('JEEP', 'Jeep', 'USA'),
  ('KATO', 'Kato', 'JAPAN'),
  ('KAWASAKI', 'Kawasaki', 'JAPAN'),
  ('KIA', 'Kia', 'KOREA'),
  ('KOBELCO', 'Kobelco', 'JAPAN'),
  ('KOMATSU', 'Komatsu', 'JAPAN'),
  ('KUBOTA', 'Kubota', 'JAPAN'),
  ('LAFORZA', 'LaForza', 'ITALY'),
  ('LAMBORGHINI', 'Lamborghini', 'ITALY'),
  ('LANCIA', 'Lancia', 'ITALY'),
  ('LAND ROVER', 'Land Rover', 'ENGLAND'),
  ('LEXUS', 'Lexus', 'JAPAN'),
  ('LINCOLN', 'Lincoln', 'USA'),
  ('LOTUS', 'Lotus', 'ENGLAND'),
  ('MASERATI', 'Maserati', 'ITALY'),
  ('MAYBACH', 'Maybach', 'GERMANY'),
  ('MAZDA', 'Mazda', 'JAPAN'),
  ('MCLAREN', 'McLaren', 'ENGLAND'),
  ('MERCEDES BENZ', 'Mercedes-Benz', 'GERMANY'),
  ('MERCURY', 'Mercury', 'USA'),
  ('MG', 'MG', 'ENGLAND'),
  ('MINI', 'Mini', 'ENGLAND'),
  ('MITSUBISHI', 'Mitsubishi', 'JAPAN'),
  ('MITSUOKA', 'Mitsuoka', 'JAPAN'),
  ('MORGAN', 'Morgan', 'ENGLAND'),
  ('NISSA', 'Nissa', 'OTHER'),
  ('NISSAN', 'Nissan', 'JAPAN'),
  ('NISSAN DIESEL (UD)', 'Nissan Diesel (UD)', 'JAPAN'),
  ('OLDSMOBILE', 'Oldsmobile', 'USA'),
  ('OPEL', 'Opel', 'GERMANY'),
  ('OTHER', 'Other', 'OTHER'),
  ('OTHER TECHNICS', 'Other Technics', 'JAPAN'),
  ('PEUGEOT', 'Peugeot', 'FRANCE'),
  ('PLYMOUTH', 'Plymouth', 'USA'),
  ('PONTIAC', 'Pontiac', 'USA'),
  ('PORSCHE', 'Porsche', 'GERMANY'),
  ('RENAULT', 'Renault', 'FRANCE'),
  ('RENAULT SAMSUNG', 'Renault Samsung', 'KOREA'),
  ('ROLLS ROYCE', 'Rolls-Royce', 'ENGLAND'),
  ('ROVER', 'Rover', 'ENGLAND'),
  ('SAAB', 'Saab', 'SWEDEN'),
  ('SATURN', 'Saturn', 'USA'),
  ('SMART', 'Smart', 'GERMANY'),
  ('SSANGYONG', 'SsangYong', 'KOREA'),
  ('STATESMAN', 'Statesman', 'OTHER'),
  ('SUBARU', 'Subaru', 'JAPAN'),
  ('SUMITOMO', 'Sumitomo', 'JAPAN'),
  ('SUZUKI', 'Suzuki', 'JAPAN'),
  ('TADANO', 'Tadano', 'JAPAN'),
  ('TCM', 'TCM', 'JAPAN'),
  ('TESLA', 'Tesla', 'USA'),
  ('TOYOTA', 'Toyota', 'JAPAN'),
  ('TVR', 'TVR', 'ENGLAND'),
  ('UNKNOWN', 'Unknown', 'OTHER'),
  ('VENTURY', 'Ventury', 'FRANCE'),
  ('VOLKSWAGEN', 'Volkswagen', 'GERMANY'),
  ('VOLVO', 'Volvo', 'SWEDEN'),
  ('WINNEBAGO', 'Winnebago', 'USA'),
  ('YAMAHA', 'Yamaha', 'JAPAN'),
  ('YANMAR', 'Yanmar', 'JAPAN'),
  ('YES!', 'YES!', 'GERMANY')
on conflict (name) do nothing;
